-- MySQL Script generated by MySQL Workbench
-- Sat Mar 22 19:40:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema botai_workspace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `auth_rule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_rule` ;

CREATE TABLE IF NOT EXISTS `auth_rule` (
  `name` VARCHAR(64) NOT NULL,
  `data` BLOB NULL DEFAULT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  `updated_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `auth_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_item` ;

CREATE TABLE IF NOT EXISTS `auth_item` (
  `name` VARCHAR(64) NOT NULL,
  `type` SMALLINT(6) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `rule_name` VARCHAR(64) NULL DEFAULT NULL,
  `data` BLOB NULL DEFAULT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  `updated_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  INDEX `rule_name` (`rule_name` ASC),
  INDEX `idx-auth_item-type` (`type` ASC),
  CONSTRAINT `auth_item_ibfk_1`
    FOREIGN KEY (`rule_name`)
    REFERENCES `auth_rule` (`name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `auth_assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_assignment` ;

CREATE TABLE IF NOT EXISTS `auth_assignment` (
  `item_name` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(64) NOT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`item_name`, `user_id`),
  INDEX `auth_assignment_user_id_idx` (`user_id` ASC),
  CONSTRAINT `auth_assignment_ibfk_1`
    FOREIGN KEY (`item_name`)
    REFERENCES `auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `auth_item_child`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_item_child` ;

CREATE TABLE IF NOT EXISTS `auth_item_child` (
  `parent` VARCHAR(64) NOT NULL,
  `child` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`parent`, `child`),
  INDEX `child` (`child` ASC),
  CONSTRAINT `auth_item_child_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `auth_item_child_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `country` ;

CREATE TABLE IF NOT EXISTS `country` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `iso_alpha2` CHAR(2) NOT NULL COMMENT 'Two-letter country code (ISO 3166-1 alpha-2)',
  `iso_alpha3` CHAR(3) NOT NULL COMMENT 'Three-letter country code (ISO 3166-1 alpha-3)',
  `iso_numeric` VARCHAR(3) NOT NULL COMMENT 'Three-digit country number (ISO 3166-1 numeric)',
  `name` VARCHAR(255) NOT NULL COMMENT 'English country name',
  `full_name` VARCHAR(255) NOT NULL COMMENT 'Full English country name',
  `original_name` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Original language name',
  `continent_code` CHAR(2) NOT NULL,
  `isd_code` VARCHAR(7) NULL DEFAULT NULL COMMENT 'International Dialing Code',
  `requires_postcode` TINYINT(1) NULL DEFAULT NULL COMMENT 'Is the postcode required when you are shipping parcel(s) to an address in the country',
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `language` ;

CREATE TABLE IF NOT EXISTS `language` (
  `language_id` VARCHAR(5) NOT NULL,
  `language` VARCHAR(3) NOT NULL,
  `country` VARCHAR(3) NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `name_ascii` VARCHAR(32) NOT NULL,
  `status` SMALLINT(6) NOT NULL,
  PRIMARY KEY (`language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `country_translation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `country_translation` ;

CREATE TABLE IF NOT EXISTS `country_translation` (
  `country_id` INT(11) NOT NULL,
  `language_id` VARCHAR(5) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `deleted` INT(11) NULL DEFAULT 0,
  PRIMARY KEY (`country_id`, `language_id`),
  INDEX `deleted` (`deleted` ASC),
  INDEX `fk_country_translation_language1_idx` (`language_id` ASC),
  CONSTRAINT `fk_country_translation_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `country` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_country_translation_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `language` (`language_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `currency` ;

CREATE TABLE IF NOT EXISTS `currency` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `iso_code` VARCHAR(3) NOT NULL,
  `symbol` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `parent_id` INT(11) NULL DEFAULT NULL,
  `auth_key` VARCHAR(32) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `signup_token` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `login_token` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `middle_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `gender` TINYINT(4) NULL DEFAULT NULL,
  `signature` TEXT NULL DEFAULT NULL,
  `last_activity` DATETIME NULL DEFAULT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `password_reset_token` (`password_reset_token` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `signup_token_UNIQUE` (`signup_token` ASC),
  INDEX `deleted` (`deleted` ASC),
  INDEX `fk_user_user1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_user_user1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `event_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_log` ;

CREATE TABLE IF NOT EXISTS `event_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `model_key` VARCHAR(255) NULL DEFAULT NULL,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `module` VARCHAR(255) NULL DEFAULT NULL,
  `controller` VARCHAR(255) NULL DEFAULT NULL,
  `action` VARCHAR(255) NULL DEFAULT NULL,
  `operation` VARCHAR(255) NULL DEFAULT NULL,
  `resource` VARCHAR(255) NULL DEFAULT NULL,
  `initial_data` MEDIUMTEXT NULL DEFAULT NULL,
  `final_data` MEDIUMTEXT NULL DEFAULT NULL,
  `ip_address` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC),
  INDEX `fk_event_log_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_event_log_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `import_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `import_file` ;

CREATE TABLE IF NOT EXISTS `import_file` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `file` VARCHAR(255) NOT NULL,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `import_sheet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `import_sheet` ;

CREATE TABLE IF NOT EXISTS `import_sheet` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `file_id` INT(11) NOT NULL,
  `number` INT(11) NULL DEFAULT NULL,
  `header` TINYINT(1) NULL DEFAULT 0,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC),
  INDEX `fk_import_sheet_import_file1_idx` (`file_id` ASC),
  CONSTRAINT `fk_import_sheet_import_file1`
    FOREIGN KEY (`file_id`)
    REFERENCES `import_file` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `import_column`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `import_column` ;

CREATE TABLE IF NOT EXISTS `import_column` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sheet_id` INT(11) NOT NULL,
  `target` VARCHAR(255) NULL DEFAULT NULL,
  `source` VARCHAR(255) NULL DEFAULT NULL,
  `source_index` TINYINT(4) NULL DEFAULT NULL,
  `field_type` VARCHAR(255) NULL DEFAULT NULL,
  `sort_order` INT(11) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC),
  INDEX `fk_import_column_import_sheet1_idx` (`sheet_id` ASC),
  CONSTRAINT `fk_import_column_import_sheet1`
    FOREIGN KEY (`sheet_id`)
    REFERENCES `import_sheet` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `language_source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `language_source` ;

CREATE TABLE IF NOT EXISTS `language_source` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(32) NULL DEFAULT NULL,
  `message` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `language_translate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `language_translate` ;

CREATE TABLE IF NOT EXISTS `language_translate` (
  `id` INT(11) NOT NULL,
  `language` VARCHAR(5) NOT NULL,
  `translation` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `language`),
  INDEX `language_translate_idx_language` (`language` ASC),
  CONSTRAINT `language_translate_ibfk_1`
    FOREIGN KEY (`language`)
    REFERENCES `language` (`language_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `language_translate_ibfk_2`
    FOREIGN KEY (`id`)
    REFERENCES `language_source` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `migration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `migration` ;

CREATE TABLE IF NOT EXISTS `migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notification` ;

CREATE TABLE IF NOT EXISTS `notification` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(8) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `message` TEXT NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  `type` TINYINT(4) NULL DEFAULT NULL,
  `icon` VARCHAR(255) NULL DEFAULT NULL,
  `color` VARCHAR(255) NULL DEFAULT NULL,
  `model_key` VARCHAR(255) NULL DEFAULT NULL,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC),
  INDEX `status` (`status` ASC),
  INDEX `type` (`type` ASC),
  INDEX `model_key` (`model_key` ASC),
  INDEX `model` (`model` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `scheduled_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scheduled_task` ;

CREATE TABLE IF NOT EXISTS `scheduled_task` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cron_expression` VARCHAR(255) NULL DEFAULT NULL,
  `app_command` TEXT NULL DEFAULT NULL,
  `shell_command` TEXT NULL DEFAULT NULL,
  `request_url` VARCHAR(255) NULL DEFAULT NULL,
  `request_config` TEXT NULL DEFAULT NULL,
  `resource` VARCHAR(255) NULL DEFAULT NULL,
  `resource_key` VARCHAR(255) NULL DEFAULT NULL,
  `application` VARCHAR(255) NULL DEFAULT NULL,
  `type` SMALLINT(6) NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `session` ;

CREATE TABLE IF NOT EXISTS `session` (
  `id` VARCHAR(255) NOT NULL,
  `expire` INT(11) NULL DEFAULT NULL,
  `data` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `setting` ;

CREATE TABLE IF NOT EXISTS `setting` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type` TINYINT(4) NULL DEFAULT NULL,
  `setting` MEDIUMTEXT NOT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `deleted` (`deleted` ASC),
  INDEX `fk_setting_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_setting_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `template` ;

CREATE TABLE IF NOT EXISTS `template` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` SMALLINT(6) NOT NULL,
  `variant` SMALLINT(6) NULL DEFAULT NULL,
  `section` TINYINT(4) NULL DEFAULT NULL,
  `default` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `template_translation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `template_translation` ;

CREATE TABLE IF NOT EXISTS `template_translation` (
  `template_id` INT(11) NOT NULL,
  `language_id` VARCHAR(5) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `subject` VARCHAR(255) NULL DEFAULT NULL,
  `header` MEDIUMTEXT NULL DEFAULT NULL,
  `footer` MEDIUMTEXT NULL DEFAULT NULL,
  `content` MEDIUMTEXT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`template_id`, `language_id`),
  INDEX `fk_template_translation_template1_idx` (`template_id` ASC),
  INDEX `fk_template_translation_language1_idx` (`language_id` ASC),
  INDEX `deleted` (`deleted` ASC),
  CONSTRAINT `fk_template_translation_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `language` (`language_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_template_translation_template1`
    FOREIGN KEY (`template_id`)
    REFERENCES `template` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `user_has_notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_has_notification` ;

CREATE TABLE IF NOT EXISTS `user_has_notification` (
  `user_id` INT(11) NOT NULL,
  `notification_id` INT(11) NOT NULL,
  `seen` TINYINT(1) NULL DEFAULT 0 COMMENT 'Indicates if the notification was seen by the user.',
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `notification_id`),
  INDEX `fk_user_has_notification_notification1_idx` (`notification_id` ASC),
  INDEX `fk_user_has_notification_user1_idx` (`user_id` ASC),
  INDEX `seen` (`seen` ASC),
  CONSTRAINT `fk_user_has_notification_notification1`
    FOREIGN KEY (`notification_id`)
    REFERENCES `notification` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_notification_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `backup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `backup` ;

CREATE TABLE IF NOT EXISTS `backup` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `file_size` INT(11) NOT NULL DEFAULT 0,
  `data` MEDIUMTEXT NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integration` ;

CREATE TABLE IF NOT EXISTS `integration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `data` MEDIUMTEXT NULL DEFAULT NULL,
  `expire_at` DATETIME NULL DEFAULT NULL,
  `type` SMALLINT NULL DEFAULT NULL,
  `sandbox` TINYINT(1) NOT NULL DEFAULT 0,
  `default` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vector_store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vector_store` ;

CREATE TABLE IF NOT EXISTS `vector_store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `openai_id` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `tokens_per_file` INT NULL DEFAULT 0,
  `expire_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assistant` ;

CREATE TABLE IF NOT EXISTS `assistant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vector_store_id` INT NULL DEFAULT NULL,
  `openai_id` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `gpt_model` VARCHAR(255) NULL DEFAULT NULL,
  `instructions` TEXT NULL DEFAULT NULL,
  `temperature` DECIMAL(15,2) NOT NULL DEFAULT 1.00,
  `top_p` DECIMAL(15,2) NOT NULL DEFAULT 1.00,
  `default` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_assistant_vector_store1_idx` (`vector_store_id` ASC),
  INDEX `deleted` (`deleted` ASC),
  CONSTRAINT `fk_assistant_vector_store1`
    FOREIGN KEY (`vector_store_id`)
    REFERENCES `vector_store` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vector_store_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vector_store_file` ;

CREATE TABLE IF NOT EXISTS `vector_store_file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vector_store_id` INT NULL DEFAULT NULL,
  `openai_id` VARCHAR(255) NULL DEFAULT NULL,
  `openai_status` VARCHAR(255) NULL DEFAULT NULL,
  `openai_message` VARCHAR(255) NULL DEFAULT NULL,
  `file` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC),
  INDEX `fk_vector_store_file_vector_store1_idx` (`vector_store_id` ASC),
  CONSTRAINT `fk_vector_store_file_vector_store1`
    FOREIGN KEY (`vector_store_id`)
    REFERENCES `vector_store` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thread`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thread` ;

CREATE TABLE IF NOT EXISTS `thread` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `openai_id` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message` ;

CREATE TABLE IF NOT EXISTS `message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `thread_id` INT NOT NULL,
  `assistant_id` INT NULL DEFAULT NULL,
  `openai_id` VARCHAR(255) NULL DEFAULT NULL,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  `content` MEDIUMTEXT NULL DEFAULT NULL,
  `completed_at` DATETIME NULL DEFAULT NULL,
  `incomplete_at` DATETIME NULL DEFAULT NULL,
  `incomplete_reason` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_message_assistant1_idx` (`assistant_id` ASC),
  INDEX `fk_message_thread1_idx` (`thread_id` ASC),
  INDEX `deleted` (`deleted` ASC),
  CONSTRAINT `fk_message_assistant1`
    FOREIGN KEY (`assistant_id`)
    REFERENCES `assistant` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_message_thread1`
    FOREIGN KEY (`thread_id`)
    REFERENCES `thread` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `participant` ;

CREATE TABLE IF NOT EXISTS `participant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `gender` TINYINT(4) NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `deleted` (`deleted` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `page` ;

CREATE TABLE IF NOT EXISTS `page` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `website` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `url` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `content` MEDIUMTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `characters` INT(11) NULL DEFAULT 0,
  `counter` INT(11) NULL DEFAULT 0,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
