<?php

use yii\db\Migration;

/**
 * Handles the creation of table `country`.
 */
class m180216_050535_create_country_table extends Migration
{
	/**
	 * @var array The country table contains the list of countries.
	 */
	protected $countries = [
		['AD', 'AND', '020', 'Andorra', 'Principality of Andorra', null, 'EU', '376', 0, 1, 0],
		['AE', 'ARE', '784', 'United Arab Emirates', 'United Arab Emirates', null, 'AS', '971', 0, 1, 0],
		['AF', 'AFG', '004', 'Afghanistan', 'Islamic Republic of Afghanistan', null, 'AS', '93', 0, 1, 0],
		['AG', 'ATG', '028', 'Antigua and Barbuda', 'Antigua and Barbuda', null, 'NA', '1268', 0, 1, 0],
		['AI', 'AIA', '660', 'Anguilla', 'Anguilla', null, 'NA', '1264', 0, 1, 0],
		['AL', 'ALB', '008', 'Albania', 'Republic of Albania', null, 'EU', '355', 0, 1, 0],
		['AM', 'ARM', '051', 'Armenia', 'Republic of Armenia', null, 'AS', '374', 0, 1, 0],
		['AN', 'ANT', '530', 'Netherlands Antilles', 'Netherlands Antilles', null, 'NA', '599', 0, 1, 0],
		['AO', 'AGO', '024', 'Angola', 'Republic of Angola', null, 'AF', '244', 0, 1, 0],
		['AQ', 'ATA', '010', 'Antarctica', 'Antarctica (the territory South of 60 deg S)', null, 'AN', '672', 0, 1, 0],
		['AR', 'ARG', '032', 'Argentina', 'Argentine Republic', null, 'SA', '54', 0, 1, 0],
		['AS', 'ASM', '016', 'American Samoa', 'American Samoa', null, 'OC', '684', 0, 1, 0],
		['AT', 'AUT', '040', 'Austria', 'Republic of Austria', null, 'EU', '43', 0, 1, 0],
		['AU', 'AUS', '036', 'Australia', 'Commonwealth of Australia', null, 'OC', '61', 0, 1, 0],
		['AW', 'ABW', '533', 'Aruba', 'Aruba', null, 'NA', '297', 0, 1, 0],
		['AX', 'ALA', '248', 'Åland', 'Åland Islands', null, 'EU', '358', 0, 1, 0],
		['AZ', 'AZE', '031', 'Azerbaijan', 'Republic of Azerbaijan', null, 'AS', '994', 0, 1, 0],
		['BA', 'BIH', '070', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', null, 'EU', '387', 0, 1, 0],
		['BB', 'BRB', '052', 'Barbados', 'Barbados', null, 'NA', '1246', 0, 1, 0],
		['BD', 'BGD', '050', 'Bangladesh', 'People\'s Republic of Bangladesh', null, 'AS', '880', 0, 1, 0],
		['BE', 'BEL', '056', 'Belgium', 'Kingdom of Belgium', null, 'EU', '32', 0, 1, 0],
		['BF', 'BFA', '854', 'Burkina Faso', 'Burkina Faso', null, 'AF', '226', 0, 1, 0],
		['BG', 'BGR', '100', 'Bulgaria', 'Republic of Bulgaria', null, 'EU', '359', 0, 1, 0],
		['BH', 'BHR', '048', 'Bahrain', 'Kingdom of Bahrain', null, 'AS', '973', 0, 1, 0],
		['BI', 'BDI', '108', 'Burundi', 'Republic of Burundi', null, 'AF', '257', 0, 1, 0],
		['BJ', 'BEN', '204', 'Benin', 'Republic of Benin', null, 'AF', '229', 0, 1, 0],
		['BL', 'BLM', '652', 'Saint Barthélemy', 'Saint Barthelemy', null, 'NA', '590', 0, 1, 0],
		['BM', 'BMU', '060', 'Bermuda', 'Bermuda', null, 'NA', '1441', 0, 1, 0],
		['BN', 'BRN', '096', 'Brunei Darussalam', 'Brunei Darussalam', null, 'AS', '673', 0, 1, 0],
		['BO', 'BOL', '068', 'Bolivia', 'Republic of Bolivia', null, 'SA', '591', 0, 1, 0],
		['BR', 'BRA', '076', 'Brazil', 'Federative Republic of Brazil', null, 'SA', '55', 0, 1, 0],
		['BS', 'BHS', '044', 'Bahamas', 'Commonwealth of the Bahamas', null, 'NA', '1242', 0, 1, 0],
		['BT', 'BTN', '064', 'Bhutan', 'Kingdom of Bhutan', null, 'AS', '975', 0, 1, 0],
		['BV', 'BVT', '074', 'Bouvet Island', 'Bouvet Island (Bouvetoya)', null, 'AN', null, 0, 1, 0],
		['BW', 'BWA', '072', 'Botswana', 'Republic of Botswana', null, 'AF', '267', 0, 1, 0],
		['BY', 'BLR', '112', 'Belarus', 'Republic of Belarus', null, 'EU', '375', 0, 1, 0],
		['BZ', 'BLZ', '084', 'Belize', 'Belize', null, 'NA', '501', 0, 1, 0],
		['CA', 'CAN', '124', 'Canada', 'Canada', null, 'NA', '1', 0, 1, 0],
		['CC', 'CCK', '166', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', null, 'AS', '672', 0, 1, 0],
		['CD', 'COD', '180', 'Congo (Kinshasa)', 'Democratic Republic of the Congo', null, 'AF', '242', 0, 1, 0],
		['CF', 'CAF', '140', 'Central African Republic', 'Central African Republic', null, 'AF', '236', 0, 1, 0],
		['CG', 'COG', '178', 'Congo (Brazzaville)', 'Republic of the Congo', null, 'AF', '242', 0, 1, 0],
		['CH', 'CHE', '756', 'Switzerland', 'Swiss Confederation', null, 'EU', '41', 0, 1, 0],
		['CI', 'CIV', '384', 'Côte d\'Ivoire', 'Republic of Cote d\'Ivoire', null, 'AF', '225', 0, 1, 0],
		['CK', 'COK', '184', 'Cook Islands', 'Cook Islands', null, 'OC', '682', 0, 1, 0],
		['CL', 'CHL', '152', 'Chile', 'Republic of Chile', null, 'SA', '56', 0, 1, 0],
		['CM', 'CMR', '120', 'Cameroon', 'Republic of Cameroon', null, 'AF', '237', 0, 1, 0],
		['CN', 'CHN', '156', 'China', 'People\'s Republic of China', null, 'AS', '86', 0, 1, 0],
		['CO', 'COL', '170', 'Colombia', 'Republic of Colombia', null, 'SA', '57', 0, 1, 0],
		['CR', 'CRI', '188', 'Costa Rica', 'Republic of Costa Rica', null, 'NA', '506', 0, 1, 0],
		['CU', 'CUB', '192', 'Cuba', 'Republic of Cuba', null, 'NA', '53', 0, 1, 0],
		['CV', 'CPV', '132', 'Cape Verde', 'Republic of Cape Verde', null, 'AF', '238', 0, 1, 0],
		['CX', 'CXR', '162', 'Christmas Island', 'Christmas Island', null, 'AS', '61', 0, 1, 0],
		['CY', 'CYP', '196', 'Cyprus', 'Republic of Cyprus', null, 'AS', '357', 0, 1, 0],
		['CZ', 'CZE', '203', 'Czech Republic', 'Czech Republic', null, 'EU', '420', 0, 1, 0],
		['DE', 'DEU', '276', 'Germany', 'Federal Republic of Germany', null, 'EU', '49', 0, 1, 0],
		['DJ', 'DJI', '262', 'Djibouti', 'Republic of Djibouti', null, 'AF', '253', 0, 1, 0],
		['DK', 'DNK', '208', 'Denmark', 'Kingdom of Denmark', null, 'EU', '45', 0, 1, 0],
		['DM', 'DMA', '212', 'Dominica', 'Commonwealth of Dominica', null, 'NA', '1767', 0, 1, 0],
		['DO', 'DOM', '214', 'Dominican Republic', 'Dominican Republic', null, 'NA', '1809', 0, 1, 0],
		['DZ', 'DZA', '012', 'Algeria', 'People\'s Democratic Republic of Algeria', null, 'AF', '213', 0, 1, 0],
		['EC', 'ECU', '218', 'Ecuador', 'Republic of Ecuador', null, 'SA', '593', 0, 1, 0],
		['EE', 'EST', '233', 'Estonia', 'Republic of Estonia', null, 'EU', '372', 0, 1, 0],
		['EG', 'EGY', '818', 'Egypt', 'Arab Republic of Egypt', null, 'AF', '20', 0, 1, 0],
		['EH', 'ESH', '732', 'Western Sahara', 'Western Sahara', null, 'AF', '212', 0, 1, 0],
		['ER', 'ERI', '232', 'Eritrea', 'State of Eritrea', null, 'AF', '291', 0, 1, 0],
		['ES', 'ESP', '724', 'Spain', 'Kingdom of Spain', null, 'EU', '34', 0, 1, 0],
		['ET', 'ETH', '231', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', null, 'AF', '251', 0, 1, 0],
		['FI', 'FIN', '246', 'Finland', 'Republic of Finland', null, 'EU', '358', 0, 1, 0],
		['FJ', 'FJI', '242', 'Fiji', 'Republic of the Fiji Islands', null, 'OC', '679', 0, 1, 0],
		['FK', 'FLK', '238', 'Falkland Islands', 'Falkland Islands (Malvinas)', null, 'SA', '500', 0, 1, 0],
		['FM', 'FSM', '583', 'Micronesia', 'Federated States of Micronesia', null, 'OC', '691', 0, 1, 0],
		['FO', 'FRO', '234', 'Faroe Islands', 'Faroe Islands', null, 'EU', '298', 0, 1, 0],
		['FR', 'FRA', '250', 'France', 'French Republic', null, 'EU', '33', 0, 1, 0],
		['GA', 'GAB', '266', 'Gabon', 'Gabonese Republic', null, 'AF', '241', 0, 1, 0],
		['GB', 'GBR', '826', 'United Kingdom', 'United Kingdom of Great Britain & Northern Ireland', null, 'EU', '44', 1, 1, 0],
		['GD', 'GRD', '308', 'Grenada', 'Grenada', null, 'NA', '1473', 0, 1, 0],
		['GE', 'GEO', '268', 'Georgia', 'Georgia', null, 'AS', '995', 0, 1, 0],
		['GF', 'GUF', '254', 'French Guiana', 'French Guiana', null, 'SA', '594', 0, 1, 0],
		['GG', 'GGY', '831', 'Guernsey', 'Bailiwick of Guernsey', null, 'EU', '44', 0, 1, 0],
		['GH', 'GHA', '288', 'Ghana', 'Republic of Ghana', null, 'AF', '233', 0, 1, 0],
		['GI', 'GIB', '292', 'Gibraltar', 'Gibraltar', null, 'EU', '350', 0, 1, 0],
		['GL', 'GRL', '304', 'Greenland', 'Greenland', null, 'NA', '299', 0, 1, 0],
		['GM', 'GMB', '270', 'Gambia', 'Republic of the Gambia', null, 'AF', '220', 0, 1, 0],
		['GN', 'GIN', '324', 'Guinea', 'Republic of Guinea', null, 'AF', '224', 0, 1, 0],
		['GP', 'GLP', '312', 'Guadeloupe', 'Guadeloupe', null, 'NA', '590', 0, 1, 0],
		['GQ', 'GNQ', '226', 'Equatorial Guinea', 'Republic of Equatorial Guinea', null, 'AF', '240', 0, 1, 0],
		['GR', 'GRC', '300', 'Greece', 'Hellenic Republic Greece', null, 'EU', '30', 0, 1, 0],
		['GS', 'SGS', '239', 'South Georgia and South Sandwich Islands', 'South Georgia and the South Sandwich Islands', null, 'AN', '995', 0, 1, 0],
		['GT', 'GTM', '320', 'Guatemala', 'Republic of Guatemala', null, 'NA', '502', 0, 1, 0],
		['GU', 'GUM', '316', 'Guam', 'Guam', null, 'OC', '1671', 0, 1, 0],
		['GW', 'GNB', '624', 'Guinea-Bissau', 'Republic of Guinea-Bissau', null, 'AF', '245', 0, 1, 0],
		['GY', 'GUY', '328', 'Guyana', 'Co-operative Republic of Guyana', null, 'SA', '592', 0, 1, 0],
		['HK', 'HKG', '344', 'Hong Kong', 'Hong Kong Special Administrative Region of China', null, 'AS', '852', 0, 1, 0],
		['HM', 'HMD', '334', 'Heard and McDonald Islands', 'Heard Island and McDonald Islands', null, 'AN', null, 0, 1, 0],
		['HN', 'HND', '340', 'Honduras', 'Republic of Honduras', null, 'NA', '504', 0, 1, 0],
		['HR', 'HRV', '191', 'Croatia', 'Republic of Croatia', null, 'EU', '385', 0, 1, 0],
		['HT', 'HTI', '332', 'Haiti', 'Republic of Haiti', null, 'NA', '509', 0, 1, 0],
		['HU', 'HUN', '348', 'Hungary', 'Republic of Hungary', null, 'EU', '36', 0, 1, 0],
		['ID', 'IDN', '360', 'Indonesia', 'Republic of Indonesia', null, 'AS', '62', 0, 1, 0],
		['IE', 'IRL', '372', 'Ireland', 'Ireland', null, 'EU', '353', 0, 1, 0],
		['IL', 'ISR', '376', 'Israel', 'State of Israel', null, 'AS', '972', 0, 1, 0],
		['IM', 'IMN', '833', 'Isle of Man', 'Isle of Man', null, 'EU', '44', 0, 1, 0],
		['IN', 'IND', '356', 'India', 'Republic of India', null, 'AS', '91', 0, 1, 0],
		['IO', 'IOT', '086', 'British Indian Ocean Territory', 'British Indian Ocean Territory (Chagos Archipelago)', null, 'AS', '246', 0, 1, 0],
		['IQ', 'IRQ', '368', 'Iraq', 'Republic of Iraq', null, 'AS', '964', 0, 1, 0],
		['IR', 'IRN', '364', 'Iran', 'Islamic Republic of Iran', null, 'AS', '98', 0, 1, 0],
		['IS', 'ISL', '352', 'Iceland', 'Republic of Iceland', null, 'EU', '354', 0, 1, 0],
		['IT', 'ITA', '380', 'Italy', 'Italian Republic', null, 'EU', '39', 0, 1, 0],
		['JE', 'JEY', '832', 'Jersey', 'Bailiwick of Jersey', null, 'EU', '44', 0, 1, 0],
		['JM', 'JAM', '388', 'Jamaica', 'Jamaica', null, 'NA', '1876', 0, 1, 0],
		['JO', 'JOR', '400', 'Jordan', 'Hashemite Kingdom of Jordan', null, 'AS', '962', 0, 1, 0],
		['JP', 'JPN', '392', 'Japan', 'Japan', null, 'AS', '81', 0, 1, 0],
		['KE', 'KEN', '404', 'Kenya', 'Republic of Kenya', null, 'AF', '254', 0, 1, 0],
		['KG', 'KGZ', '417', 'Kyrgyzstan', 'Kyrgyz Republic', null, 'AS', '996', 0, 1, 0],
		['KH', 'KHM', '116', 'Cambodia', 'Kingdom of Cambodia', null, 'AS', '855', 0, 1, 0],
		['KI', 'KIR', '296', 'Kiribati', 'Republic of Kiribati', null, 'OC', '686', 0, 1, 0],
		['KM', 'COM', '174', 'Comoros', 'Union of the Comoros', null, 'AF', '269', 0, 1, 0],
		['KN', 'KNA', '659', 'Saint Kitts and Nevis', 'Federation of Saint Kitts and Nevis', null, 'NA', '1869', 0, 1, 0],
		['KP', 'PRK', '408', 'Korea, North', 'Democratic People\'s Republic of Korea', null, 'AS', '850', 0, 1, 0],
		['KR', 'KOR', '410', 'Korea, South', 'Republic of Korea', null, 'AS', '82', 0, 1, 0],
		['KW', 'KWT', '414', 'Kuwait', 'State of Kuwait', null, 'AS', '965', 0, 1, 0],
		['KY', 'CYM', '136', 'Cayman Islands', 'Cayman Islands', null, 'NA', '1345', 0, 1, 0],
		['KZ', 'KAZ', '398', 'Kazakhstan', 'Republic of Kazakhstan', null, 'AS', '7', 0, 1, 0],
		['LA', 'LAO', '418', 'Laos', 'Lao People\'s Democratic Republic', null, 'AS', '856', 0, 1, 0],
		['LB', 'LBN', '422', 'Lebanon', 'Lebanese Republic', null, 'AS', '961', 0, 1, 0],
		['LC', 'LCA', '662', 'Saint Lucia', 'Saint Lucia', null, 'NA', '1758', 0, 1, 0],
		['LI', 'LIE', '438', 'Liechtenstein', 'Principality of Liechtenstein', null, 'EU', '423', 0, 1, 0],
		['LK', 'LKA', '144', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', null, 'AS', '94', 0, 1, 0],
		['LR', 'LBR', '430', 'Liberia', 'Republic of Liberia', null, 'AF', '231', 0, 1, 0],
		['LS', 'LSO', '426', 'Lesotho', 'Kingdom of Lesotho', null, 'AF', '266', 0, 1, 0],
		['LT', 'LTU', '440', 'Lithuania', 'Republic of Lithuania', null, 'EU', '8', 0, 1, 0],
		['LU', 'LUX', '442', 'Luxembourg', 'Grand Duchy of Luxembourg', null, 'EU', '352 ', 0, 1, 0],
		['LV', 'LVA', '428', 'Latvia', 'Republic of Latvia', null, 'EU', '371', 0, 1, 0],
		['LY', 'LBY', '434', 'Libya', 'Libyan Arab Jamahiriya', null, 'AF', '218', 0, 1, 0],
		['MA', 'MAR', '504', 'Morocco', 'Kingdom of Morocco', null, 'AF', '212', 0, 1, 0],
		['MC', 'MCO', '492', 'Monaco', 'Principality of Monaco', null, 'EU', '377', 0, 1, 0],
		['MD', 'MDA', '498', 'Moldova', 'Republic of Moldova', null, 'EU', '373', 0, 1, 0],
		['ME', 'MNE', '499', 'Montenegro', 'Republic of Montenegro', null, 'EU', '382', 0, 1, 0],
		['MF', 'MAF', '663', 'Saint Martin (French part)', 'Saint Martin', null, 'NA', '590', 0, 1, 0],
		['MG', 'MDG', '450', 'Madagascar', 'Republic of Madagascar', null, 'AF', '261', 0, 1, 0],
		['MH', 'MHL', '584', 'Marshall Islands', 'Republic of the Marshall Islands', null, 'OC', '692', 0, 1, 0],
		['MK', 'MKD', '807', 'Macedonia', 'Republic of Macedonia', null, 'EU', '389', 0, 1, 0],
		['ML', 'MLI', '466', 'Mali', 'Republic of Mali', null, 'AF', '223', 0, 1, 0],
		['MM', 'MMR', '104', 'Myanmar', 'Union of Myanmar', null, 'AS', '95', 0, 1, 0],
		['MN', 'MNG', '496', 'Mongolia', 'Mongolia', null, 'AS', '976', 0, 1, 0],
		['MO', 'MAC', '446', 'Macau', 'Macao Special Administrative Region of China', null, 'AS', '853', 0, 1, 0],
		['MP', 'MNP', '580', 'Northern Mariana Islands', 'Commonwealth of the Northern Mariana Islands', null, 'OC', '1670', 0, 1, 0],
		['MQ', 'MTQ', '474', 'Martinique', 'Martinique', null, 'NA', '596', 0, 1, 0],
		['MR', 'MRT', '478', 'Mauritania', 'Islamic Republic of Mauritania', null, 'AF', '222', 0, 1, 0],
		['MS', 'MSR', '500', 'Montserrat', 'Montserrat', null, 'NA', '1664', 0, 1, 0],
		['MT', 'MLT', '470', 'Malta', 'Republic of Malta', null, 'EU', '356', 0, 1, 0],
		['MU', 'MUS', '480', 'Mauritius', 'Republic of Mauritius', null, 'AF', '230', 0, 1, 0],
		['MV', 'MDV', '462', 'Maldives', 'Republic of Maldives', null, 'AS', '960', 0, 1, 0],
		['MW', 'MWI', '454', 'Malawi', 'Republic of Malawi', null, 'AF', '265', 0, 1, 0],
		['MX', 'MEX', '484', 'Mexico', 'United Mexican States', null, 'NA', '52', 0, 1, 0],
		['MY', 'MYS', '458', 'Malaysia', 'Malaysia', null, 'AS', '60', 0, 1, 0],
		['MZ', 'MOZ', '508', 'Mozambique', 'Republic of Mozambique', null, 'AF', '258', 0, 1, 0],
		['NA', 'NAM', '516', 'Namibia', 'Republic of Namibia', null, 'AF', '264', 0, 1, 0],
		['NC', 'NCL', '540', 'New Caledonia', 'New Caledonia', null, 'OC', '687', 0, 1, 0],
		['NE', 'NER', '562', 'Niger', 'Republic of Niger', null, 'AF', '227', 0, 1, 0],
		['NF', 'NFK', '574', 'Norfolk Island', 'Norfolk Island', null, 'OC', '672', 0, 1, 0],
		['NG', 'NGA', '566', 'Nigeria', 'Federal Republic of Nigeria', null, 'AF', '234', 0, 1, 0],
		['NI', 'NIC', '558', 'Nicaragua', 'Republic of Nicaragua', null, 'NA', '505', 0, 1, 0],
		['NL', 'NLD', '528', 'Netherlands', 'Kingdom of the Netherlands', null, 'EU', '31', 0, 1, 0],
		['NO', 'NOR', '578', 'Norway', 'Kingdom of Norway', null, 'EU', '47', 0, 1, 0],
		['NP', 'NPL', '524', 'Nepal', 'State of Nepal', null, 'AS', '977', 0, 1, 0],
		['NR', 'NRU', '520', 'Nauru', 'Republic of Nauru', null, 'OC', '674', 0, 1, 0],
		['NU', 'NIU', '570', 'Niue', 'Niue', null, 'OC', '683', 0, 1, 0],
		['NZ', 'NZL', '554', 'New Zealand', 'New Zealand', null, 'OC', '64', 0, 1, 0],
		['OM', 'OMN', '512', 'Oman', 'Sultanate of Oman', null, 'AS', '968', 0, 1, 0],
		['PA', 'PAN', '591', 'Panama', 'Republic of Panama', null, 'NA', '507', 0, 1, 0],
		['PE', 'PER', '604', 'Peru', 'Republic of Peru', null, 'SA', '51', 0, 1, 0],
		['PF', 'PYF', '258', 'French Polynesia', 'French Polynesia', null, 'OC', '689', 0, 1, 0],
		['PG', 'PNG', '598', 'Papua New Guinea', 'Independent State of Papua New Guinea', null, 'OC', '675', 0, 1, 0],
		['PH', 'PHL', '608', 'Philippines', 'Republic of the Philippines', null, 'AS', '63', 0, 1, 0],
		['PK', 'PAK', '586', 'Pakistan', 'Islamic Republic of Pakistan', null, 'AS', '92', 0, 1, 0],
		['PL', 'POL', '616', 'Poland', 'Republic of Poland', null, 'EU', '48', 0, 1, 0],
		['PM', 'SPM', '666', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', null, 'NA', '508', 0, 1, 0],
		['PN', 'PCN', '612', 'Pitcairn', 'Pitcairn Islands', null, 'OC', '64', 0, 1, 0],
		['PR', 'PRI', '630', 'Puerto Rico', 'Commonwealth of Puerto Rico', null, 'NA', '1787', 0, 1, 0],
		['PS', 'PSE', '275', 'Palestine', 'Occupied Palestinian Territory', null, 'AS', '970', 0, 1, 0],
		['PT', 'PRT', '620', 'Portugal', 'Portuguese Republic', null, 'EU', '351', 0, 1, 0],
		['PW', 'PLW', '585', 'Palau', 'Republic of Palau', null, 'OC', '680', 0, 1, 0],
		['PY', 'PRY', '600', 'Paraguay', 'Republic of Paraguay', null, 'SA', '595', 0, 1, 0],
		['QA', 'QAT', '634', 'Qatar', 'State of Qatar', null, 'AS', '974', 0, 1, 0],
		['RE', 'REU', '638', 'Reunion', 'Reunion', null, 'AF', '262', 0, 1, 0],
		['RO', 'ROU', '642', 'Romania', 'Romania', null, 'EU', '40', 0, 1, 0],
		['RS', 'SRB', '688', 'Serbia', 'Republic of Serbia', null, 'EU', '381', 0, 1, 0],
		['RU', 'RUS', '643', 'Russian Federation', 'Russian Federation', null, 'EU', '7', 0, 1, 0],
		['RW', 'RWA', '646', 'Rwanda', 'Republic of Rwanda', null, 'AF', '250', 0, 1, 0],
		['SA', 'SAU', '682', 'Saudi Arabia', 'Kingdom of Saudi Arabia', null, 'AS', '966', 0, 1, 0],
		['SB', 'SLB', '090', 'Solomon Islands', 'Solomon Islands', null, 'OC', '677', 0, 1, 0],
		['SC', 'SYC', '690', 'Seychelles', 'Republic of Seychelles', null, 'AF', '248', 0, 1, 0],
		['SD', 'SDN', '736', 'Sudan', 'Republic of Sudan', null, 'AF', '249', 0, 1, 0],
		['SE', 'SWE', '752', 'Sweden', 'Kingdom of Sweden', null, 'EU', '46', 0, 1, 0],
		['SG', 'SGP', '702', 'Singapore', 'Republic of Singapore', null, 'AS', '65', 0, 1, 0],
		['SH', 'SHN', '654', 'Saint Helena', 'Saint Helena', null, 'AF', '290', 0, 1, 0],
		['SI', 'SVN', '705', 'Slovenia', 'Republic of Slovenia', null, 'EU', '386', 0, 1, 0],
		['SJ', 'SJM', '744', 'Svalbard and Jan Mayen Islands', 'Svalbard & Jan Mayen Islands', null, 'EU', '47', 0, 1, 0],
		['SK', 'SVK', '703', 'Slovakia', 'Slovakia (Slovak Republic)', null, 'EU', '421', 0, 1, 0],
		['SL', 'SLE', '694', 'Sierra Leone', 'Republic of Sierra Leone', null, 'AF', '232', 0, 1, 0],
		['SM', 'SMR', '674', 'San Marino', 'Republic of San Marino', null, 'EU', '378', 0, 1, 0],
		['SN', 'SEN', '686', 'Senegal', 'Republic of Senegal', null, 'AF', '221', 0, 1, 0],
		['SO', 'SOM', '706', 'Somalia', 'Somali Republic', null, 'AF', '252', 0, 1, 0],
		['SR', 'SUR', '740', 'Suriname', 'Republic of Suriname', null, 'SA', '597', 0, 1, 0],
		['ST', 'STP', '678', 'Sao Tome and Principe', 'Democratic Republic of Sao Tome and Principe', null, 'AF', '239', 0, 1, 0],
		['SV', 'SLV', '222', 'El Salvador', 'Republic of El Salvador', null, 'NA', '503', 0, 1, 0],
		['SY', 'SYR', '760', 'Syria', 'Syrian Arab Republic', null, 'AS', '963', 0, 1, 0],
		['SZ', 'SWZ', '748', 'Swaziland', 'Kingdom of Swaziland', null, 'AF', '268', 0, 1, 0],
		['TC', 'TCA', '796', 'Turks and Caicos Islands', 'Turks and Caicos Islands', null, 'NA', '1649', 0, 1, 0],
		['TD', 'TCD', '148', 'Chad', 'Republic of Chad', null, 'AF', '235', 0, 1, 0],
		['TF', 'ATF', '260', 'French Southern Lands', 'French Southern Territories', null, 'AN', null, 0, 1, 0],
		['TG', 'TGO', '768', 'Togo', 'Togolese Republic', null, 'AF', '228', 0, 1, 0],
		['TH', 'THA', '764', 'Thailand', 'Kingdom of Thailand', null, 'AS', '66', 0, 1, 0],
		['TJ', 'TJK', '762', 'Tajikistan', 'Republic of Tajikistan', null, 'AS', '992', 0, 1, 0],
		['TK', 'TKL', '772', 'Tokelau', 'Tokelau', null, 'OC', '690', 0, 1, 0],
		['TL', 'TLS', '626', 'Timor-Leste', 'Democratic Republic of Timor-Leste', null, 'AS', '670', 0, 1, 0],
		['TM', 'TKM', '795', 'Turkmenistan', 'Turkmenistan', null, 'AS', '993', 0, 1, 0],
		['TN', 'TUN', '788', 'Tunisia', 'Tunisian Republic', null, 'AF', '216', 0, 1, 0],
		['TO', 'TON', '776', 'Tonga', 'Kingdom of Tonga', null, 'OC', '676', 0, 1, 0],
		['TR', 'TUR', '792', 'Turkey', 'Republic of Turkey', null, 'AS', '90', 0, 1, 0],
		['TT', 'TTO', '780', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', null, 'NA', '1868', 0, 1, 0],
		['TV', 'TUV', '798', 'Tuvalu', 'Tuvalu', null, 'OC', '688', 0, 1, 0],
		['TW', 'TWN', '158', 'Taiwan', 'Taiwan', null, 'AS', '886', 0, 1, 0],
		['TZ', 'TZA', '834', 'Tanzania', 'United Republic of Tanzania', null, 'AF', '255', 0, 1, 0],
		['UA', 'UKR', '804', 'Ukraine', 'Ukraine', null, 'EU', '380', 0, 1, 0],
		['UG', 'UGA', '800', 'Uganda', 'Republic of Uganda', null, 'AF', '256', 0, 1, 0],
		['UM', 'UMI', '581', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', null, 'OC', '1', 0, 1, 0],
		['US', 'USA', '840', 'United States of America', 'United States of America', null, 'NA', '1', 0, 1, 0],
		['UY', 'URY', '858', 'Uruguay', 'Eastern Republic of Uruguay', null, 'SA', '598', 0, 1, 0],
		['UZ', 'UZB', '860', 'Uzbekistan', 'Republic of Uzbekistan', null, 'AS', '998', 0, 1, 0],
		['VA', 'VAT', '336', 'Vatican City', 'Holy See (Vatican City State)', null, 'EU', '39', 0, 1, 0],
		['VC', 'VCT', '670', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', null, 'NA', '1784', 0, 1, 0],
		['VE', 'VEN', '862', 'Venezuela', 'Bolivarian Republic of Venezuela', null, 'SA', '58', 0, 1, 0],
		['VG', 'VGB', '092', 'Virgin Islands, British', 'British Virgin Islands', null, 'NA', '1284', 0, 1, 0],
		['VI', 'VIR', '850', 'Virgin Islands, U.S.', 'United States Virgin Islands', null, 'NA', '1340', 0, 1, 0],
		['VN', 'VNM', '704', 'Vietnam', 'Socialist Republic of Vietnam', null, 'AS', '84', 0, 1, 0],
		['VU', 'VUT', '548', 'Vanuatu', 'Republic of Vanuatu', null, 'OC', '678', 0, 1, 0],
		['WF', 'WLF', '876', 'Wallis and Futuna Islands', 'Wallis and Futuna', null, 'OC', '681', 0, 1, 0],
		['WS', 'WSM', '882', 'Samoa', 'Independent State of Samoa', null, 'OC', '685', 0, 1, 0],
		['YE', 'YEM', '887', 'Yemen', 'Yemen', null, 'AS', '967', 0, 1, 0],
		['YT', 'MYT', '175', 'Mayotte', 'Mayotte', null, 'AF', '269', 0, 1, 0],
		['ZA', 'ZAF', '710', 'South Africa', 'Republic of South Africa', null, 'AF', '27', 0, 1, 0],
		['ZM', 'ZMB', '894', 'Zambia', 'Republic of Zambia', null, 'AF', '260', 0, 1, 0],
		['ZW', 'ZWE', '716', 'Zimbabwe', 'Republic of Zimbabwe', null, 'AF', '263', 0, 1, 0],
	];

	/**
	 * @inheritdoc
	 */
	public function up()
	{
		$tableOptions = null;
		if ($this->db->driverName === 'mysql') {
			$tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
		}

		$this->createTable('{{%country}}', [
			'id' => $this->primaryKey(),
			'iso_alpha2' => $this->char(2)->notNull()->comment('Two-letter country code (ISO 3166-1 alpha-2)'),
			'iso_alpha3' => $this->char(3)->notNull()->comment('Three-letter country code (ISO 3166-1 alpha-3)'),
			'iso_numeric' => $this->string(3)->notNull()->comment('Three-digit country number (ISO 3166-1 numeric)'),
			'name' => $this->string(255)->notNull()->comment('English country name'),
			'full_name' => $this->string(255)->notNull()->comment('Full English country name'),
			'original_name' => $this->string(255)->defaultValue(null)->comment('Original language name'),
			'continent_code' => $this->char(2)->notNull()->comment('Continent two-letter code'),
			'isd_code' => $this->string(7)->defaultValue(null)->comment('International Dialing Code'),
			'requires_postcode' => $this->smallInteger(4)->defaultValue(null)->comment('Is the postcode required for shipping parcel(s) to an address in the country'),
			'status' => $this->smallInteger(4)->defaultValue(null),
			'deleted' => $this->smallInteger(4)->defaultValue(0),
		], $tableOptions);

		$this->batchInsert('{{%country}}', [
			'iso_alpha2',
			'iso_alpha3',
			'iso_numeric',
			'name',
			'full_name',
			'original_name',
			'continent_code',
			'isd_code',
			'requires_postcode',
			'status',
			'deleted',
		], $this->countries);

		$this->createIndex('deleted', '{{%country}}', 'deleted');
	}

	/**
	 * @inheritdoc
	 */
	public function down()
	{
		$this->dropTable('{{%country}}');
	}
}
