<?php

namespace common\widgets\datatable;

use Yii;
use yii\helpers\Html;
use yii\helpers\Json;
use tws\helpers\Url;
use yii\web\JsExpression;

class ActionColumn extends BaseDataTableColumn
{
	/**
	 * @inheritdoc
	 */
	public $className = 'action-column col-autowidth';

	/**
	 * @inheritdoc
	 */
	public $orderable = false;

	/**
	 * @inheritdoc
	 */
	public $searchable = false;

	/**
	 * @var int The number of buttons per row.
	 */
	public $buttonsPerRow = 5;

	/**
	 * @var array The buttons list in action column.
	 */
	public $buttons = [];

	/**
	 * @inheritdoc
	 */
	public function init()
	{
		parent::init();

		$this->initDefaults();

		if (empty($this->data)) {
			$this->render = $this->buildRender();
		}
	}

	/**
	 * Initializes default attributes.
	 */
	protected function initDefaults()
	{
		// Default buttons
		$defaultButtons = [
			'view' => [
				'visible' => true,
				'url' => ['view', 'id' => new JsExpression('id')],
				'content' => '<span class="fa fa-eye"></span>',
				'options' => [
					'class' => 'action-view btn btn-xs btn-info',
					'title' => Yii::t('common', 'View'),
					'data' => [
						'toggle' => 'tooltip',
					],
				],
			],
			'update' => [
				'visible' => true,
				'url' => ['update', 'id' => new JsExpression('id')],
				'content' => '<span class="fa fa-edit"></span>',
				'options' => [
					'class' => 'action-update btn btn-xs btn-primary',
					'title' => Yii::t('common', 'Update'),
					'data' => [
						'toggle' => 'tooltip',
					],
				],
			],
			'delete' => [
				'visible' => true,
				'url' => ['delete', 'id' => new JsExpression('id')],
				'content' => '<span class="fa fa-trash"></span>',
				'options' => [
					'class' => 'action-delete btn btn-xs btn-danger',
					'title' => Yii::t('common', 'Delete'),
					'data' => [
						'toggle' => 'tooltip',
						'dt-operation' => 'delete',
						'dt-confirm' => Yii::t('common', 'Are you sure you want to perform this operation?'),
					],
				],
			],
		];
		// Buttons array
		$buttons = [];
		// Loop through the buttons
		foreach ($this->buttons as $name => $button) {
			if (is_string($button) && array_key_exists($button, $defaultButtons)) {
				// If only the button name is provided, use it from the defaults
				$buttons[$button] = $defaultButtons[$button];
			} elseif (is_bool($button) && array_key_exists($name, $defaultButtons)) {
				// If the button is provided as a string and has the visibility set (eg. 'update' => true)
				$buttons[$name] = $defaultButtons[$name];
				// Use it from the defaults, but with the provided visibility
				$buttons[$name]['visible'] = $button;
			} elseif (is_array($button)) {
				// Use the button configuration array
				$buttons[$name] = $button;
			}
		}
		// Set the buttons
		$this->buttons = array_filter($buttons, function ($item) {
			return $item['visible'] === true;
		});
		// Center single buttons in the column
		if (count($this->buttons) === 1) {
			$this->className .= ' text-center';
		}

		// Hide this column if there are no actions to display
		if (empty($this->data) && empty($this->buttons)) {
			$this->visible = false;
		}

		// Action column default filter
		if (!isset($this->filter)) {
			$this->filter = Html::tag('button', '<span class="fa fa-times"></span>', [
				'type' => 'button',
				'class' => 'btn btn-xs btn-default',
				'title' => Yii::t('common', 'Clear column filters'),
				'data' => [
					'toggle' => 'tooltip',
					'dt-clear-filters' => true,
				],
			]);
		}
	}

	/**
	 * Creates an array of buttons.
	 *
	 * @return array
	 */
	protected function createButtons()
	{
		// Array of buttons
		$buttons = [];
		// Loop through the existing buttons
		foreach ($this->buttons as $name => $button) {
			// Check if the tag should be a link with an URL set to href attribute
			if (isset($button['url']) && $button['url'][0] !== '#') {
				// Ensure that url is always generated by the router
				$url = [$button['url'][0]];
				// Remove the route from the array
				unset($button['url'][0]);
				// Loop through the remaining URL params and set the params to be replaced on DataTable column render
				foreach ($button['url'] as $param => $value) {
					// Check the value type
					if ($value instanceof JsExpression) {
						// If the value is an expression, then prepare it to be replaced by DataTable row property
						$url[$param] = "__{$value}__";
					} else {
						// Use the value as it is provided
						$url[$param] = $value;
					}
				}
				// Set the href attribute
				$button['options']['href'] = Url::to($url);
			}
			// Create the HTML tag
			$buttons[$name]['tag'] = Html::tag($button['url'] ? 'a' : 'button', $button['content'], $button['options']);
			$buttons[$name]['visible'] = is_null($button['visible']) ? true : $button['visible'];
		}
		// Return the generated buttons
		return $buttons;
	}

	/**
	 * Builds a custom renderer.
	 *
	 * @return JsExpression|string
	 */
	protected function buildRender()
	{
		// If a custom render is set
		if (!empty($this->render)) {
			return $this->render;
		}
		// Create a new render function
		return new JsExpression("function (data, type, row, meta) {
			var buttons = " . Json::encode($this->createButtons()) . ";
			var buttonsPerRow = " . $this->buttonsPerRow . ";
			var columnButtons = ['<div>'];
			var i = 1;
			
			$.each(buttons, function (name, button) {
				if (typeof button.visible !== 'boolean') {
					var isVisible = true;
					$.each(button.visible, function (index, value) {
						isVisible &= eval(row[value[1]] + value[0] + value[2]);  
					});
					if (!isVisible) {
						return;
					}
				}
				columnButtons.push(button.tag.replace(/(__\w+__)/gmi, function (match, tag, char) {
					var param = match.replace(/__/gmi, '');
					return row[param];
				}));
				
				if (i % buttonsPerRow == 0) {
					columnButtons.push('</div><div>');
				}
				
				i++;
			});
			
			columnButtons.push('</div>');
			
			return columnButtons.join('');
		}");
	}
}
